bitbake_target: core-image-ros-world
configuration_name: latest
bitbake_ref: master
oecore_ref: master
localconf: |
  LICENSE_FLAGS_WHITELIST = "commercial"
  DISTRO_FEATURES += "directfb opengl x11"
dependencies:
  - url: git://git.openembedded.org/meta-openembedded
    ref: master
    layers:
      - meta-oe
      - meta-python
      - meta-multimedia
